trigger: none

pool:
    vmImage: "windows-latest"

resources:
  pipelines:
    - pipeline: YDD
      source: 'Build-YamlDeploymentDemo' #matches the build pipeline in DevOps
      branch: master
      trigger:
        branches:
        - '*'

variables:
  - group: 'YamlDeploymentVarGrp' #variable group located in Library tab
  - name: AzureSubscription
    value: 'Azure Personal Sub' #should match an AzureRM connection in DevOps

stages:
  - stage: Download_DB
    dependsOn: []
    jobs:
      - job: Download_DB
        steps:
          - download: YDD
            displayName: 'Download databases'
            artifact: database
            
  - stage: Download_API
    dependsOn: []
    jobs:
      - job: Download_API
        steps:
          - download: YDD
            displayName: 'Download API'
            artifact: api
            
  - stage: Download_Functions
    dependsOn: []
    jobs:
      - job: Download_Functions
        steps:
          - download: YDD
            displayName: 'Download Functions'
            artifact: functions

  - stage: Download_Web
    dependsOn: []
    jobs:
      - job: Download_Web
        steps:
          - download: YDD
            displayName: 'Download Webapp'
            artifact: web

  - stage: Provision_Common_Resources
    dependsOn: []
    variables:
      ResourceGroup: YamlDeploymentDemoRG #resource group in Azure
      SiteName: yamldeploydemo
    jobs:
      - job: Provision_Common_Resources
        steps:
          - template: Templates/provision-common-resources.yml
            parameters:
              ResourceGroup: $(ResourceGroup)
              Region: $(Region)
              SqlServerName: $(SqlServerName)
              SqlServerAdminUser: $(SqlServerAdminUser)
              SqlserverAdminPassword: $(SqlserverAdminPassword)
              WebServerFarmName: $(WebServerFarmName)
              ApplicationInsightsName: $(SiteName)-appinsights

  - stage: Deploy_DB
    dependsOn: 
      - Download_DB
      - Provision_Common_Resources
    variables:
      ResourceGroup: YamlDeploymentDemoRG #resource group in Azure
      EnvironmentName: YamlDeploymentEnv
      SiteName: yamldeploydemo
    jobs:
      - deployment: Deploy_DB
        environment: ${{ variables.EnvironmentName }}
        pool:
          vmImage: 'windows-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: database
                - template: Templates/deploy-db.yml
                  parameters:
                    SqlServerAdminUser: $(SqlServerAdminUser)
                    SqlserverAdminPassword: $(SqlserverAdminPassword)
                    SqlServerNameFqdn: $(SqlServerNameFqdn)
                    DbName: ydd-db
