trigger: none

resources:
  pipelines:
    - pipeline: YDD
      source: Build-YamlDeploymentDemo #matches the build pipeline in DevOps

variables:
  - group: 'YamlDeploymentDemoRG'
  - name: AzureSubscription
    value: 'Azure Personal Sub' #should match an AzureRM connection in DevOps

stages:
  - stage: Deploy_All
    dependsOn: []
    variables:
      ResourceGroup: YamlDeploymentDemoGroup
      EnvironmentName: YamlDeploymentEnv
      SiteName: yaml-deployment
      RedisDatabaseId: 3
    jobs:
      - deployment: YDD_Full_Deploy
        environment: ${{ variables.EnvironmentName }}
        pool:
          vmImage: 'windows-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                
                - template: Templates/ydd.yml
                  parameters:
                    ResourceGroup: $(ResourceGroup)
                    Region: $(Region)
                    SiteName: $(SiteName)
                    SqlServerName: $(SqlServerName)
                    SqlServerAdminUser: $(SqlServerAdminUser)
                    SqlserverAdminPassword: $(SqlserverAdminPassword)
                    SqlServerNameFqdn: $(SqlServerNameFqdn)
                    DbName: custexqa0-db #todo
                    WebServerFarmName: $(WebServerFarmName)
                    WebServerResourceGroup: $(WebServerResourceGroup)
                    ApplicationInsightsName: $(SiteName)-appinsights
                    StorageAccountName: $(SiteName)ydd
                    FunctionAppName: $(SiteName)-fn
                    CustomExServiceBusName: $(SiteName)-servicebus
                    ApiName: $(SiteName)-api
                    JwtSigningKey: Qf47nscNoWPo5QpZbR4Bp2nzFQXBFHv5HPVA02Ltmz6BNJKFRwEfRK8Hzw #todo
                    TokenExpiryInMinutes: 5
                    StolenBikeCheckFunctionInterval: 0 */5 * * * *

                    
