trigger: none

pool:
    vmImage: "windows-latest"

resources:
  pipelines:
    - pipeline: YDD
      source: 'Build-YamlDeploymentDemo' #matches the build pipeline in DevOps
      branch: master
      trigger:
        branches:
        - '*'
              
steps:
- script: echo Triggered by source pipeline
  displayName: 'Proba proba'

                    
