trigger: none

pool:
    vmImage: "windows-latest"

resources:
  pipelines:
    - pipeline: YDD
      source: 'Build-YamlDeploymentDemo' #matches the build pipeline in DevOps
      branch: master
      trigger:
        branches:
        - '*'

variables:
  - group: 'YamlDeploymentVarGrp' #variable group located in Library tab
  - name: AzureSubscription
    value: 'Azure Personal Sub 2' #should match an AzureRM connection in DevOps

stages:

  - stage: Provision_Common_Resources
    dependsOn: []
    variables:
      ResourceGroup: YamlDeploymentDemoRG-Split #resource group in Azure
      SiteName: yamldeploydemo
    jobs:
      - job: Provision_Common_Resources
        steps:
          - template: Templates/provision-common-resources.yml
            parameters:
              ResourceGroup: $(ResourceGroup)
              Region: $(Region)
              SqlServerName: $(SqlServerName)
              SqlServerAdminUser: $(SqlServerAdminUser)
              SqlserverAdminPassword: $(SqlserverAdminPassword)
              WebServerFarmName: $(WebServerFarmName)
              ApplicationInsightsName: $(SiteName)-appinsights

  - stage: Deploy_DB
    dependsOn: 
      - Provision_Common_Resources
    variables:
      ResourceGroup: YamlDeploymentDemoRG-Split #resource group in Azure
      EnvironmentName: YamlDeploymentEnv
      SiteName: yamldeploydemo
    jobs:
      - deployment: Deploy_DB
        environment: ${{ variables.EnvironmentName }}
        pool:
          vmImage: 'windows-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: Templates/deploy-db.yml
                  parameters:
                    SqlServerAdminUser: $(SqlServerAdminUser)
                    SqlserverAdminPassword: $(SqlserverAdminPassword)
                    SqlServerNameFqdn: $(SqlServerNameFqdn)
                    DbName: ydd-db
                    
  - stage: Provision_Storage
    dependsOn: 
      - Provision_Common_Resources
    variables:
      ResourceGroup: YamlDeploymentDemoRG-Split #resource group in Azure
      SiteName: yamldeploydemo
    jobs:
      - job: Provision_Storage
        steps:
          - template: Templates/provision-storage.yml
            parameters:
              ResourceGroup: $(ResourceGroup)
              Region: $(Region)
              StorageAccountName: $(SiteName)storage
              
  - stage: Provision_WebApps
    dependsOn: 
      - Provision_Common_Resources
    variables:
      ResourceGroup: YamlDeploymentDemoRG-Split #resource group in Azure
      SiteName: yamldeploydemo
    jobs:
      - job: Provision_WebApps
        steps:
          - template: Templates/provision-webapps.yml
            parameters:
              ResourceGroup: $(ResourceGroup)
              Region: $(Region)
              SqlServerName: $(SqlServerName)
              WebServerFarmName: $(WebServerFarmName)
              WebAppName: $(SiteName)-web
              ApiName: $(SiteName)-api