trigger: none

pool:
    vmImage: "windows-latest"

resources:
  pipelines:
    - pipeline: sourcePipeline
      source: 'Pipelines Trigger - Source'
      branch: master
      trigger:
        branches:
        - '*'
              
steps:
- script: echo Triggered by source pipeline
  displayName: 'Proba proba'

                    
